USE InstantRide;
DELIMITER $$
CREATE PROCEDURE VATCalculator()
BEGIN
SELECT
TRAVEL_ID,
ROUND(
CASE
WHEN TRAVEL_DISCOUNT IS NULL THEN TRAVEL_PRICE * 0.08
ELSE (TRAVEL_PRICE (1 - TRAVEL_DISCOUNT)) 0.08
END
, 2) AS VAT
FROM
TRAVELS
ORDER BY
TRAVEL_ID;
END $$
DELIMITER ;