USE InstantRide;
DROP PROCEDURE IF EXISTS EmailList;
DELIMITER $$
CREATE PROCEDURE EmailList(OUT result TEXT)
BEGIN
    SELECT GROUP_CONCAT(USER_EMAIL ORDER BY USER_ID SEPARATOR ';') INTO result FROM USERS;
END$$
DELIMITER ;
CALL EmailList(@email_list_result);
SELECT @email_list_result;