SELECT
  L1.INV_NUM,
  L1.LINE_NUM AS "L.LINE_NUM",
  P1.PROD_SKU AS "P.PROD_SKU",
  P1.PROD_DESCRIPT AS "P.PROD_DESCRIPT",
  L2.LINE_NUM AS "L2.LINE_NUM",
  P2.PROD_SKU AS "P2.PROD_SKU",
  P2.PROD_DESCRIPT AS "P2.PROD_DESCRIPT",
  B.BRAND_ID
FROM
  LGLINE AS L1
JOIN
  LGPRODUCT AS P1
ON
  L1.PROD_SKU = P1.PROD_SKU
JOIN
  LGBRAND AS B
ON
  P1.BRAND_ID = B.BRAND_ID
JOIN
  LGLINE AS L2
ON
  L1.INV_NUM = L2.INV_NUM -- Same Invoice Number
JOIN
  LGPRODUCT AS P2
ON
  L2.PROD_SKU = P2.PROD_SKU
WHERE
  P1.PROD_CATEGORY = 'Sealer'
  AND P2.PROD_CATEGORY <> 'Sealer' -- P2 is not a Sealer
  AND P2.PROD_CATEGORY <> 'Primer' -- Exclude Primer, if it's not considered a "top coat"
  AND P1.BRAND_ID = P2.BRAND_ID   -- Same Brand
  AND L1.LINE_NUM < L2.LINE_NUM   -- Ensures 'sealer' line number is always less than 'top coat' line number
ORDER BY
  L1.INV_NUM ASC,
  L1.LINE_NUM ASC,
  L2.LINE_NUM DESC;