DROP PROCEDURE IF EXISTS UpdateCharter;

 DELIMITER //

CREATE PROCEDURE UpdateCharter()
BEGIN
UPDATE CHARTER C
INNER JOIN MODEL M ON C.AC_NUMBER = M.MOD_CODE
SET C.CHAR_WAIT_CHG  = M.MOD_WAIT_CHG;

END//

 DELIMITER ;

 CALL UpdateCharter();

 