SELECT T.TRAVEL_ID,
    T.TRAVEL_START_TIME,
    T.TRAVEL_END_TIME,
    T.TRAVEL_START_LOCATION,
    T.TRAVEL_END_LOCATION,
    T.TRAVEL_PRICE,
    T.DRIVER_ID,
    T.CAR_ID, 
    T.USER_ID,
    T.TRAVEL_DISCOUNT
FROM TRAVELS T
    JOIN CARS C ON T.CAR_ID = C.CAR_ID
WHERE C.CAR_PLATE LIKE "BB-883%";