SELECT
P.PAT_ID,
P.PAT_LNAME,
COUNT(C.CHECK_NUM) AS `NUM CHECKOUTS`,
COUNT(DISTINCT C.BOOK_NUM) AS `NUM DIFFERENT BOOKS`
FROM
PATRON P
JOIN
CHECKOUT C ON C.PAT_ID = P.PAT_ID
GROUP BY
P.PAT_ID,
P.PAT_LNAME
HAVING COUNT(C.CHECK_NUM) > 2

ORDER BY 
`NUM DIFFERENT BOOKS` DESC, 
`NUM CHECKOUTS` DESC,
P.PAT_ID


