SELECT 
    pat_id,
    ROUND(AVG(CHECK_IN_DATE - CHECK_OUT_DATE),2) AS  `AVERAGE DAYS KEPT`
FROM 
    CHECKOUT
GROUP BY 
    pat_id
HAVING 
    COUNT(*) >= 3
ORDER BY 
      `AVERAGE DAYS KEPT` DESC, pat_id ASC;