SELECT
C.CHECK_NUM,
B.BOOK_NUM,
P.PAT_ID,
C.CHECK_OUT_DATE,
C.CHECK_DUE_DATE 
FROM
PATRON P
JOIN
CHECKOUT C ON P.PAT_ID = C.PAT_ID
JOIN
BOOK B ON B.BOOK_NUM = C.BOOK_NUM
ORDER BY
C.CHECK_OUT_DATE DESC, C.CHECK_NUM;