SELECT
C.CUS_CODE, I.INV_NUMBER, I.INV_DATE, P.P_DESCRIPT, L.LINE_UNITS, L.LINE_PRICE
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
ORDER BY 
C.CUS_CODE, I.INV_NUMBER, P.P_DESCRIPT;

SELECT
C.CUS_CODE, 
I.INV_NUMBER,
P.P_DESCRIPT,
L.LINE_UNITS AS "UNITS BOUGHT",
L.LINE_PRICE AS "UNIT PRICE",
ROUND(L.LINE_PRICE * L.LINE_UNITS,2) AS SUBTOTAL
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
ORDER BY 
C.CUS_CODE, I.INV_NUMBER, P.P_DESCRIPT;


SELECT
C.CUS_CODE, 
C.CUS_BALANCE,
SUM(ROUND(L.LINE_PRICE * L.LINE_UNITS,2)) AS "Total Purchases", COUNT(L.LINE_NUMBER) AS "Number of Purchases", ROUND(AVG(L.LINE_PRICE * L.LINE_UNITS), 2) AS "Average Purchase Amount"
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
GROUP BY
CUS_CODE
ORDER BY 
C.CUS_CODE;