SELECT
C.CUS_CODE, I.INV_NUMBER, I.INV_DATE, P.P_DESCRIPT, L.LINE_UNITS, L.LINE_PRICE
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
ORDER BY 
C.CUS_CODE, I.INV_NUMBER, P.P_DESCRIPT;

SELECT
C.CUS_CODE, 
I.INV_NUMBER,
P.P_DESCRIPT,
L.LINE_UNITS AS "UNITS BOUGHT",
L.LINE_PRICE AS "UNIT PRICE",
ROUND(L.LINE_PRICE * L.LINE_UNITS,2) AS SUBTOTAL
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
ORDER BY 
C.CUS_CODE, I.INV_NUMBER, P.P_DESCRIPT;


SELECT
C.CUS_CODE, 
C.CUS_BALANCE,
SUM(ROUND(L.LINE_PRICE * L.LINE_UNITS,2)) AS "Total Purchases", COUNT(L.LINE_NUMBER) AS "Number of Purchases", ROUND(AVG(L.LINE_PRICE * L.LINE_UNITS), 2) AS "Average Purchase Amount"
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
GROUP BY
CUS_CODE
ORDER BY 
C.CUS_CODE;



SELECT
I.INV_NUMBER, 
SUM(ROUND(L.LINE_PRICE * L.LINE_UNITS,2)) AS "INVOICE TOTAL"
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
GROUP BY
I.INV_NUMBER
ORDER BY 
I.INV_NUMBER;



SELECT
C.CUS_CODE,
I.INV_NUMBER, 
SUM(ROUND(L.LINE_PRICE * L.LINE_UNITS,2)) AS "INVOICE TOTAL"
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
GROUP BY
I.INV_NUMBER
ORDER BY 
C.CUS_CODE;


SELECT
C.CUS_CODE,
I.INV_NUMBER, 
SUM(ROUND(L.LINE_PRICE * L.LINE_UNITS,2)) AS "INVOICE TOTAL"
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
GROUP BY
I.INV_NUMBER
ORDER BY 
C.CUS_CODE; 


SELECT
C.CUS_CODE,
ROUND(COUNT(DISTINCT I.INV_NUMBER),0) AS "NUMBER OF INVOICES", 
SUM(ROUND(L.LINE_PRICE * L.LINE_UNITS,2)) AS "TOTAL CUSTOMER PURCHASES"
FROM
CUSTOMER C 
JOIN      
INVOICE I
ON
I.CUS_CODE = C.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
GROUP BY
C.CUS_CODE
ORDER BY 
C.CUS_CODE; 

WITH BALANCES AS (
    SELECT
        C.CUS_CODE,
        C.CUS_BALANCE
    FROM
        CUSTOMER AS C
    JOIN 
        INVOICE I
    ON
    I.CUS_CODE = C.CUS_CODE 
)
SELECT
 CUS_CODE,
 CUS_BALANCE
FROM
   BALANCES AS B;  

WITH BALANCES AS (
    SELECT
        ROUND(MIN(C.CUS_BALANCE),2) AS `MINIMUM BALANCE`,
        ROUND(MAX(C.CUS_BALANCE),2) AS `MAXIMUM BALANCE`,
        ROUND(AVG(C.CUS_BALANCE),2) AS `AVERAGE BALANCE`
    FROM
        CUSTOMER AS C
    JOIN 
        INVOICE I
    ON
    I.CUS_CODE = C.CUS_CODE 
)
SELECT
    B.`MINIMUM BALANCE`,
    B.`MAXIMUM BALANCE`,
    B.`AVERAGE BALANCE`
FROM
   BALANCES AS B;  