WITH BALANCES AS (
    SELECT
        ROUND(MIN(C.CUS_BALANCE),2) AS `MINIMUM BALANCE`,
        ROUND(MAX(C.CUS_BALANCE),2) AS `MAXIMUM BALANCE`,
        ROUND(AVG(C.CUS_BALANCE),2) AS `AVERAGE BALANCE`
    FROM
        CUSTOMER AS C
    JOIN 
        INVOICE I
    ON
    I.CUS_CODE = C.CUS_CODE 
)
SELECT
    B.`MINIMUM BALANCE`,
    B.`MAXIMUM BALANCE`,
    B.`AVERAGE BALANCE`
FROM
   BALANCES AS B;  