SELECT
C.CUS_CODE, 
C.CUS_BALANCE,
SUM(ROUND(L.LINE_PRICE * L.LINE_UNITS,2)) AS "Total Purchases", COUNT(L.LINE_NUMBER) AS "Number of Purchases"
FROM
CUSTOMER C 
JOIN
INVOICE I
ON
C.CUS_CODE = I.CUS_CODE
JOIN
Ch07_SaleCoLINE L
ON 
L.INV_NUMBER = I.INV_NUMBER
JOIN
PRODUCT P
ON
L.P_Code = P.P_CODE
GROUP BY
CUS_CODE
ORDER BY 
C.CUS_CODE;