
SELECT DISTINCT
   SUM(C.CUS_BALANCE) AS `TOTAL BALANCE`,
   MIN(C.CUS_BALANCE) AS `MINIMUM BALANCE`,
   MAX(C.CUS_BALANCE) AS `MAXIMUM BALANCE`,
   ROUND(AVG(C.CUS_BALANCE),2) AS `AVERAGE BALANCE`

FROM
   CUSTOMER C  
LEFT JOIN
INVOICE I 
ON I.CUS_CODE = C.CUS_CODE
WHERE I.CUS_CODE IS NULL

