SELECT DISTINCT
E.EMP_NUM,E.EMP_LNAME, ROUND(SUM(A.ASSIGN_HOURS),1) AS SUMOFASSIGN_HOURS, SUM(A.ASSIGN_CHARGE) AS SUMOFASSIGN_CHARGE 
FROM 
EMPLOYEE E
JOIN 
ASSIGNMENT A
ON
A.EMP_NUM = E.EMP_NUM
GROUP BY
EMP_NUM, EMP_LNAME
ORDER BY 
EMP_NUM;