SELECT
P.PROJ_NAME, P.PROJ_VALUE,P.PROJ_BALANCE, E.EMP_LNAME, E.EMP_FNAME, E.EMP_INITIAL, J.JOB_CODE, J.JOB_DESCRIPTION, J.JOB_CHG_HOUR 
FROM 
      JOB J
JOIN 
    EMPLOYEE E 
ON E.JOB_CODE = J.JOB_CODE
JOIN
 PROJECT P
ON 
P.EMP_NUM = E.EMP_NUM
ORDER BY P.PROJ_VALUE;

SELECT DISTINCT
PROJ_NUM
FROM 
PROJECT
ORDER BY 
PROJ_NUM;

SELECT DISTINCT
ASSIGN_NUM, EMP_NUM,PROJ_NUM,ASSIGN_CHARGE, ROUND(ASSIGN_HOURS * ASSIGN_CHG_HR,2) AS CALC_ASSIGN_CHARGE
FROM 
ASSIGNMENT
ORDER BY 
ASSIGN_NUM;

SELECT DISTINCT
E.EMP_NUM,E.EMP_LNAME, SUM(A.ASSIGN_HOURS) AS SUMOFASSIGN_HOURS, SUM(A.ASSIGN_CHARGE) AS SUMOFASSIGN_CHARGE 
FROM 
EMPLOYEE E
JOIN 
ASSIGNMENT A
ON
A.EMP_NUM = E.EMP_NUM
GROUP BY
EMP_NUM, EMP_LNAME
ORDER BY 
EMP_NUM;

SELECT
PROJ_NUM, ROUND(SUM(ASSIGN_HOURS),1) , SUM(ASSIGN_CHARGE)
FROM
ASSIGNMENT
GROUP BY
PROJ_NUM
ORDER BY 
PROJ_NUM;