SELECT
*
FROM
DRIVERS;

SELECT 
DATE_FORMAT(DRIVER_START_DATE, "%Y-%m-%d") AS DRIVER_START_DATE
FROM 
DRIVERS;

SELECT
 DRIVER_ID, DRIVER_RATING
 FROM
 DRIVERS
 WHERE DRIVER_RATING > 4
 ORDER BY DRIVER_RATING;


SELECT
 DRIVER_ID, DRIVER_RATING
 FROM
 DRIVERS
 WHERE DRIVER_RATING > 4
 ORDER BY DRIVER_RATING DESC;

 SELECT
 DRIVER_ID, DRIVER_RATING
 FROM
 DRIVERS
 WHERE DRIVER_RATING > 4
 ORDER BY DRIVER_RATING;

SELECT 
 U.USER_ID, TIMEDIFF(T.TRAVEL_END_TIME, T.TRAVEL_START_TIME) AS 'TRAVEL_TIME '
 FROM 
 TRAVELS T, USERS U
 WHERE
 T.USER_ID = U.USER_ID;