SELECT
*
FROM
DRIVERS;

SELECT 
DATE_FORMAT(DRIVER_START_DATE, "%Y-%m-%d") AS DRIVER_START_DATE
FROM 
DRIVERS;

SELECT
 DRIVER_ID, DRIVER_RATING
 FROM
 DRIVERS
 WHERE DRIVER_RATING > 4
 ORDER BY DRIVER_RATING;


SELECT
 DRIVER_ID, DRIVER_RATING
 FROM
 DRIVERS
 WHERE DRIVER_RATING > 4
 ORDER BY DRIVER_RATING DESC;

 SELECT
 DRIVER_ID, DRIVER_RATING
 FROM
 DRIVERS
 WHERE DRIVER_RATING > 4
 ORDER BY DRIVER_RATING;

SELECT 
 U.USER_ID, TIMEDIFF(T.TRAVEL_END_TIME, T.TRAVEL_START_TIME) AS 'TRAVEL_TIME '
 FROM 
 TRAVELS T, USERS U
 WHERE
 T.USER_ID = U.USER_ID;

 SELECT
T.USER_ID, MAX(DATE_FORMAT(T.TRAVEL_END_TIME, "%M")) AS LAST_TRAVEL_MONTH
FROM
TRAVELS T
GROUP BY T.USER_ID;

SELECT
    T.USER_ID,
    DATE_FORMAT(LAST_DAY(T.TRAVEL_END_TIME), '%Y-%m-%d') AS LAST_TRAVEL_MONTH,
    DATE_FORMAT(ADDDATE(LAST_DAY(T.TRAVEL_END_TIME), INTERVAL 1 WEEK),  '%Y-%m-%d') AS NOTIFICATION
FROM
    TRAVELS T;

    SELECT 
T.TRAVEL_ID, ROUND(SUM(TRAVEL_PRICE*TRAVEL_DISCOUNT),2) AS DISCOUNT_AMOUNT
FROM TRAVELS T 
WHERE TRAVEL_DISCOUNT > 0
GROUP BY T.TRAVEL_ID;