SELECT
    T.USER_ID,
    DATE_FORMAT(LAST_DAY(T.TRAVEL_END_TIME), '%Y-%m-%d') AS LAST_TRAVEL_MONTH,
    DATE_FORMAT(ADDDATE(LAST_DAY(T.TRAVEL_END_TIME), INTERVAL 1 WEEK),  '%Y-%m-%d') AS NOTIFICATION
FROM
    TRAVELS T;