DROP TRIGGER IF EXISTS trg_updatecustbalance2;

DELIMITER $$
CREATE TRIGGER trg_updatecustbalance2
AFTER DELETE ON INVOICE
FOR EACH ROW
BEGIN
    UPDATE CUSTOMER
    SET CUST_BALANCE = CUST_BALANCE - OLD.INV_AMOUNT
    WHERE CUST_NUM = OLD.CUST_NUM;
END$$
DELIMITER ;
