SELECT
    U1.USER_ID AS UserID_1,
    U1.USER_FIRST_NAME AS FirstName,
    U1.USER_LAST_NAME AS LastName,
    U1.USER_EMAIL AS Email_1,
    U2.USER_ID AS UserID_2,
    U2.USER_EMAIL AS Email_2
FROM
    USERS U1
JOIN
    USERS U2 ON U1.USER_FIRST_NAME = U2.USER_FIRST_NAME
            AND U1.USER_LAST_NAME = U2.USER_LAST_NAME
            AND U1.USER_ID != U2.USER_ID;