SELECT
    U1.USER_ID AS USER_ID,
    U1.USER_FIRST_NAME AS USER_FIRST_NAME,
    U1.USER_LAST_NAME AS USER_LAST_NAME,
    U1.USER_EMAIL
FROM
    USERS U1
JOIN
    USERS U2 ON U1.USER_FIRST_NAME = U2.USER_FIRST_NAME
            AND U1.USER_LAST_NAME = U2.USER_LAST_NAME
            AND U1.USER_ID != U2.USER_ID;