SELECT
*
FROM TRAVELS T
WHERE T.DRIVER_ID IN
(SELECT
D.DRIVER_ID
FROM
DRIVERS D
WHERE
D.DRIVER_RATING < 4
);

-- Write your query below and then click "Run Query" to execute it. To save multiple queries, click the "+" icon on the left.
SELECT
DRIVER_ID, DRIVER_FIRST_NAME, DRIVER_LAST_NAME
FROM
DRIVERS
WHERE
DRIVERS.DRIVER_ID = 
(SELECT 
D.DRIVER_ID
FROM
DRIVERS D
WHERE 
D.DRIVER_ID != ALL (SELECT DISTINCT T.DRIVER_ID FROM TRAVELS T)
);

SELECT
CAR_ID, ROUND(AVG(ROUND(TRAVEL_PRICE * TRAVEL_DISCOUNT,2)),2) AS DISCOUNT_AMOUNT
FROM
TRAVELS 
WHERE TRAVEL_DISCOUNT > 0
GROUP BY CAR_ID;

