-- Drop EMP_2 if it already exists to ensure a clean creation
DROP TABLE IF EXISTS EMP_2;

-- Create the EMP_2 table structure with EMP_PCT and PROJ_NUM columns
CREATE TABLE EMP_2 (
    EMP_NUM      VARCHAR(3)   NOT NULL PRIMARY KEY,
    EMP_LNAME    VARCHAR(15)  NOT NULL,
    EMP_FNAME    VARCHAR(15)  NOT NULL,
    EMP_INITIAL  VARCHAR(1),
    EMP_HIREDATE DATE,
    JOB_CODE     VARCHAR(3),
    EMP_PCT      DECIMAL(4,2),
    PROJ_NUM     VARCHAR(4) -- Increased column size to VARCHAR(4)
);

-- Insert specified rows individually into EMP_2 with EMP_PCT and PROJ_NUM values
INSERT INTO EMP_2 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE, EMP_PCT, PROJ_NUM)
VALUES ('101', 'News', 'John', 'G', '2000-11-08', '502', 5.00, '3.85');

INSERT INTO EMP_2 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE, EMP_PCT, PROJ_NUM)
VALUES ('105', 'Johnson', 'Alice', 'K', '1997-02-01', '502', 5.00, '3.85');

INSERT INTO EMP_2 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE, EMP_PCT, PROJ_NUM)
VALUES ('107', 'Alonzo', 'Maria', 'D', '1997-10-10', '501', 5.15, 'NULL');

-- Insert the new rows you provided
INSERT INTO EMP_2 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE, EMP_PCT, PROJ_NUM)
VALUES ('102', 'Senior', 'David', 'H', '1989-07-12', '501', 10.00, NULL);

INSERT INTO EMP_2 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE, EMP_PCT, PROJ_NUM)
VALUES ('104', 'Ramoras', 'Anne', 'K', '1991-11-15', '501', 10.00, NULL);

INSERT INTO EMP_2 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE, EMP_PCT, PROJ_NUM)
VALUES ('106', 'Smithfield', 'William', NULL, '2008-06-22', '500', 10.00, NULL);

INSERT INTO EMP_2 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE, EMP_PCT, PROJ_NUM)
VALUES ('108', 'Washington', 'Ralph', 'B', '1995-08-22', '501', 10.00, NULL);

INSERT INTO EMP_2 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE, EMP_PCT, PROJ_NUM)
VALUES ('109', 'Smith', 'Larry', 'W', '2001-07-18', '501', 10.00, NULL);

-- Add .15 to the EMP_PCT of Maria D. Alonzo


-- Select all data from EMP_2 to verify contents
SELECT *
FROM EMP_2;
