TRUNCATE TABLE EMP_2;

INSERT INTO EMP_2 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE, EMP_PCT, PROJ_NUM)
SELECT
    EMP_NUM,
    EMP_LNAME,
    EMP_FNAME,
    EMP_INITIAL,
    EMP_HIREDATE,
    JOB_CODE,
    NULL AS EMP_PCT,   -- Assuming these new columns will be NULL for inserted rows
    NULL AS PROJ_NUM
FROM
    EMP_1
WHERE
    EMP_LNAME = 'News' OR EMP_LNAME = 'Johnson' OR EMP_LNAME = 'Alonzo';
